merge to simplify testing for plugin
Signed-off-by: Adam Scerra <ascerra@redhat.com>

diff --git a/.github/workflows/checks-sealights.yaml b/.github/workflows/checks-sealights.yaml
--- a/.github/workflows/checks-sealights.yaml
+++ b/.github/workflows/checks-sealights.yaml
@@ -37,8 +37,6 @@ jobs:
 
   Initialize:
     runs-on: ubuntu-latest
-    env:
-      SEALIGHTS_LOG_LEVEL: none
     outputs:
       bsid: ${{ steps.sealights-scan.outputs.bsid }}
     steps:
@@ -101,7 +99,7 @@ jobs:
           echo "[Sealights] Configuring SeaLights to scan the pull request branch"
           echo "Latest commit sha: ${LATEST_COMMIT_SHA}"
           echo "PR Number: ${PULL_REQUEST_NUMBER}"
-          ./slcli config create-pr-bsid --app ec-cli --target-branch "main" --pull-request-number ${PULL_REQUEST_NUMBER} --latest-commit ${LATEST_COMMIT_SHA} --repository-url https://github.com/enterprise-contract/ec-cli.git
+          ./slcli config create-pr-bsid --app ec-cli-test --target-branch "main" --pull-request-number ${PULL_REQUEST_NUMBER} --latest-commit ${LATEST_COMMIT_SHA} --repository-url https://github.com/enterprise-contract/ec-cli.git
         env:
           PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
           LATEST_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
@@ -110,7 +108,7 @@ jobs:
         if: env.on-event == 'push'
         run: |
           echo "[Sealights] Configuring SeaLights to scan the main branch after pull request was closed"
-          ./slcli config create-bsid --app ec-cli --branch main --build ${LATEST_COMMIT_SHA}
+          ./slcli config create-bsid --app ec-cli-test --branch main --build ${LATEST_COMMIT_SHA}
         env:
           LATEST_COMMIT_SHA: ${{ github.sha }}
 
@@ -153,32 +151,32 @@ jobs:
       - name: Test
         run: make test
 
-  Acceptance:
-    runs-on: ubuntu-latest
-    needs: [Initialize, Test]
-    env:
-      BSID: ${{ needs.Initialize.outputs.bsid }}
-      SEALIGHTS_LOG_LEVEL: none
-      SEALIGHTS_CONNECTION_TIMEOUT: 120s
-    steps:
-      - name: Restore workspace
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}
-          key: workspace-${{ github.run_id }}
+  # Acceptance:
+  #   runs-on: ubuntu-latest
+  #   needs: Initialize
+  #   env:
+  #     BSID: ${{ needs.Initialize.outputs.bsid }}
+  #     SEALIGHTS_CONNECTION_TIMEOUT: 120s
+  #   steps:
+  #     - name: Restore workspace
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ github.workspace }}
+  #         key: workspace-${{ github.run_id }}
 
-      - name: Update podman
-        run: |
-          "${GITHUB_WORKSPACE}/hack/ubuntu-podman-update.sh"
-      - name: Create a test session
-        run: ./slcli test start-stage --bsid=$BSID --testStage "Acceptance Tests"
+  #     - name: Update podman
+  #       run: |
+  #         "${GITHUB_WORKSPACE}/hack/ubuntu-podman-update.sh"
+      
+  #     - name: Create a test session
+  #       run: ./slcli test start-stage --bsid=$BSID --testStage "Acceptance Tests"
 
-      - name: Acceptance test
-        run: make acceptance-sealights
+  #     - name: Acceptance test
+  #       run: make acceptance-sealights
 
-      - name: Upload test results, end test session
-        if: success() || failure()
-        run: |
-          cat ./junit-acceptance.xml
-          ./slcli test upload-reports --bsid=$BSID --report-location ./junit-acceptance.xml
-          ./slcli test end-stage --bsid=$BSID --executionId "Acceptance Tests"
+  #     - name: Upload test results, end test session
+  #       if: success() || failure()
+  #       run: |
+  #         cat ./junit-acceptance.xml
+  #         ./slcli test upload-reports --bsid=$BSID --report-location ./junit-acceptance.xml
+  #         ./slcli test end-stage --bsid=$BSID --executionId "Acceptance Tests"
